### ISSUE TITLE
Not able to run builds on travis after using this plugin

### ISSUE THREAD

**Issue by mukesh-mt** [SwiftGen/SwiftGenPlugin#11]
Getting following error:
```
The following build commands failed:
    Validate plug-in “SwiftGenPlugin” in package “swiftgenplugin”
```
Sample project: [SwiftGenTest](https://github.com/mukesh-mt/SwiftGenTest)
Travis build logs: https://app.travis-ci.com/github/mukesh-mt/SwiftGenTest/builds/259180201

**Comment by odisei369** [comment]
You could pass xcodebuild flag `-skipPackagePluginValidation` to skip this validation

**Comment by markltownsend** [comment]
Do you know if travis is using an Intel machine? Having the same issue when running on a AWS Intel Mac Dedicated Host.  Works fine on an M1 Mac.

**Comment by mukesh-mt** [comment]
Yes, it’s Intel mac

**Comment by markltownsend** [comment]
Adding in the skipValidation  argument to xcodebuild worked for me.

**Comment by mukesh-mt** [comment]
Thanks! `-skipPackagePluginValidation` worked for me too.

**Comment by TheMetalCode** [comment]
While `-skipPackagePluginValidation` remains an effective workaround, I should add that I've seen this error occur on an AWS mac2 (aka M1) host, so I'm not certain it's entirely Intel related.
